spring:
  server:
    port: 8080

  application:
    name: peluditos-ya-server

  datasource:
    url: jdbc:postgresql://localhost:5432/peluditos_db
    username: peluditos_user
    password: peluditos_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # Change from 'update' to 'create-drop' for testing
    show-sql: true
    defer-datasource-initialization: true # Important: This makes SQL initialization run after Hibernate

  sql:
    init:
      mode: always

  debug: true
